# Generated by Django 4.1.3 on 2022-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category_quizzes_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_right',
            new_name='is_correct',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
