# Generated by Django 4.1.3 on 2022-12-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_body_alter_question_technique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
